### ISSUE TITLE
For use in OS X

### ISSUE THREAD

**Issue by arjunmayilvaganan** [ParkerK/selfrestraint#15]
Is there a `.app` compiled application for OS X yet?
Or, at least can anyone point to instructions to use this in a OS X from source?

**Comment by pklaus** [comment]
On OSX, rather use the original: https://github.com/SelfControlApp/selfcontrol

**Comment by arjunmayilvaganan** [comment]
@pklaus Thanks for your response. I'm actually using the original only. The original is written in Objective-C (which I don't understand). I was wanting to experiment with `selfrestraint` as it is being written in Python. Hence the question.

**Comment by pklaus** [comment]
OK, I see. This software seems to be abandoned since 2014. "Add compiled .app" is still listed in the [ToDo in the README](https://github.com/ParkerK/selfrestraint#to-do). I guess you would have to package it yourself (and check that it still runs properly with the latest version of OSX).

**Comment by arjunmayilvaganan** [comment]
This issue is being closed due to inactivity. Please feel to re-open.
